### ISSUE TITLE
Finish data import one-time script

### ISSUE THREAD

**Issue by thewindsofwinter** [thewindsofwinter/JHMC-scripts#10]
For more information, see the Airtable Data Import document

- [X] A record is created for each student under “Students”
- [X] A record is created for each school under “Schools” with
    - [X] Coach name
    - [X] Coach email
    - [X] Correct division
 - [X] An easy way to add other fields (like in the sample data, Lunch Order Option and % with cell phone)
 - [X] Based on the competitions the student is in, infer their grade level
 - [x] Each student is linked to a school, and each school has a set of students (see current example data)
 - [x] Each student is correctly assigned their Tests

Just keeping this here for @phultquist if he isn't done with the rest already

**Comment by thewindsofwinter** [comment]
Okay, time to fix this :) forecast this will be done by tonight

**Comment by thewindsofwinter** [comment]
I think this is done, although to implement teams I'll have to do a little more. Closing for now.

**Comment by phultquist** [comment]
YES ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
