### ISSUE TITLE
Clock goes 1:01 -> 0:60

### ISSUE THREAD

**Issue by phultquist** [thewindsofwinter/JHMC-scripts#14]
Simple bug. Obviously happens at all minutes.

**Comment by phultquist** [comment]
* Clock goes 1:01 -> 0:60, which is obviously a small and stupid bug
* If you leave the tab, the timer pauses 🤨 which confuses me because I thought I subtracted dates but whatever

**Comment by thewindsofwinter** [comment]
Has this ever been fixed? If so, should I close?

**Comment by thewindsofwinter** [comment]
Fixed with latest commit
