### ISSUE TITLE
load-students.js doesn't work for a partially-empty roster registration

### ISSUE THREAD

**Issue by phultquist** [thewindsofwinter/JHMC-scripts#21]
Some schools don't have all positions filled for the competition, so, for example, they only have 3 people in a team or have 2 people in an individual contest.

When this happens, a couple of errors may show up:
```
TypeError: Cannot read property 'push' of undefined
```
also 
```
TypeError: Cannot read property 'push' of undefined
```

The errors depend on which roster registration you use -- I'm not sure why there are two different errors, but one happens with `sampleRoster.csv` and the other happens with `2021data.csv`.

**Comment by thewindsofwinter** [comment]
Okay, I will get on it today

**Comment by thewindsofwinter** [comment]
Fixed and completed issue, I'm closing
